name: Env Manual Approval

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fake step with 30s delay
        id: fake-step
        run: |
          echo "Starting fake step..."
          sleep 30
          echo "Completed fake step..."
  deploy:
    runs-on: ubuntu-latest
    environment: release
    needs: build-and-test
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Check approval status
        id: check-approval
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Make API request using gh CLI and capture the response
          response=$(gh api /repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/approvals)
          # Extract values using jq and store them in bash variables
          state=$(echo "$response" | jq -r '.[0].state')
          comment=$(echo "$response" | jq -r '.[0].comment')
          user_login=$(echo "$response" | jq -r '.[0].user.login')
          # Output the variables to confirm extraction
          echo "State: $state"
          echo "Comment: $comment"
          echo "User Login: $user_login"
      - name: Deploy to production
        env:
          PROD_TEST_SECRET: ${{ secrets.PROD_TEST_SECRET }}
        run: |
          # Deploy to production with the secret
          echo "Deploying to production..."
