name: Create branches
on:
  # To manually trigger test 123
  workflow_dispatch:
    inputs:
      git-tag:
        description: 'Git tag'
        required: true
      new-branch-name:
        description: 'New branch name'
        required: true


jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.git-tag }}
      - name: Append SNAPSHOT to the version
        run: |
          FILE="build.txt"
          # Get the version from build.txt
          VERSION=$(awk -F'=' '/^version=/ {print $2}' "$FILE")
          echo "Current version is $VERSION"
          #if version is empty, exit
          if [ -z "$VERSION" ]; then
          echo "Version not found in $FILE"
          exit 1
          fi
          #Add -SNAPSHOT to the version
          NEW_VERSION="${VERSION}-SNAPSHOT"
          echo "New version is $NEW_VERSION"
          # Set the new version in build.txt
          sed -i.bak "s/^version=.*/version=${NEW_VERSION}/" $FILE
      - name: Create Branch
        shell: bash
        run: |
          # Set version
          git config --global user.email "bot@ghaction.com"
          git config --global user.name "Release BOT"
          git checkout -b ${{ inputs.new-branch-name }}
          # commit the changes
            git commit -am "${{ inputs.new-branch-name }}-version-update"
          # Push the branch
          git push --set-upstream origin ${{ inputs.new-branch-name }}
          
