name: Create branches
on:
  # To manually trigger
  workflow_dispatch:
    inputs:
      git-tag:
        description: 'Git tag'
        required: true
      new-branch-name:
        description: 'New branch name'
        required: true


jobs:
  create-branche-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          git-ref: ${{ inputs.git-tag }}
      - name: Create Branch
        shell: bash
        run: |
          # Set version
          git config --global user.email "bot@ghaction.com"
          git config --global user.name "Release BOT"
          git checkout -b ${{ inputs.new-branch-name }}
          # Push the branch
          git push --set-upstream origin ${{ inputs.new-branch-name }}
          
